name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch if it's different.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js (if you're using a JavaScript framework)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Use the version required by your project

    # Step 3: Install dependencies and build
    - name: Install dependencies and build
      run: |
        npm install
        npm run build  # Change this command if your build process differs

    # Step 4: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public/html  # Replace './build' with your build output directory
